routes/web.php
<?php

use App\Artigo;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {
    if (isset($req->busca) && $req->busca != '') {
        $busca = $req->busca;
        //busca no db;
        $lista = Artigo::listaArtigosSite(3, $busca);
    } else {
        $lista = Artigo::listaArtigosSite(3);
        $busca = "";
    }


    return view('site', compact('lista', 'busca'));
})->name('site');
Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
        return view('artigo',compact('artigo'));
    }
    return redirect()->route('site');
})->name('artigo');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:eAutor');;
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArtigosController')->middleware('can:eAutor');
    Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
    Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
    Route::resource('adm', 'AdminController')->middleware('can:eAdmin');

});

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<pagina tamanho="10">
    <painel titulo="Dashboard">

        <migalhas v-bind:lista="{{$listaMigalhas}}"></migalhas>
        <div class="row">
            @can('eAutor')
            <div class="col-md-4">
                <caixa v-bind:qtd="{{$count['artigos']}}" titulo="Artigos" url="{{route('artigos.index')}}" cor="orange" icon="ion ion-pie-graph"></caixa>
            </div>
            @endcan
            @can('eAdmin')
            <div class="col-md-4">
                <caixa v-bind:qtd="{{$count['usuarios']}}" titulo="Usuarios" url="{{route('usuarios.index')}}" cor="blue" icon="ion ion-person-stalker"></caixa>
            </div>
            <div class="col-md-4">
                <caixa v-bind:qtd="{{$count['autores']}}" titulo="Autores" url="{{route('autores.index')}}" cor="red" icon="ion ion-person"></caixa>
            </div>
            <div class="col-md-4">
                <caixa v-bind:qtd="{{$count['admin']}}" titulo="Admin" url="{{route('adm.index')}}" cor="green" icon="ion ion-person"></caixa>
            </div>
            @endcan


        </div>
    </painel>
</pagina>
@endsection

resources/views/artigo.blade.php
@extends('layouts.app')

@section('content')
<pagina tamanho="10">
    <painel>
    <h2 align='center'>{{$artigo->titulo}}</h2>
    <h4 align='center'>{{$artigo->descricao}}</h4>

        <div class="containerimg">
            <img class="img" src="{{'/'.$artigo->imagem}}" alt="...">
        </div>
        <br>
        <p><b>{{$artigo->titulo}}</b> -
            <small>{{$artigo->descricao}}</small>
        </p>
        <p>
            <small><b>Por: {{$artigo->user->name}}</b></small>
        </p>
        <hr>
    <p>
        {!!$artigo->conteudo!!}
    </p>

        <interacoes></interacoes>
        <div id="disqus_thread"></div>

        <p align='center'> <small>Por: {{$artigo->user->name}} - {{date('d/m/Y',strtotime($artigo->data))}}</small></p>
    </painel>
</pagina>

@endsection
<style>
    .img {
        width: 100%;
    }


</style>

resources/views/site.blade.php
@extends('layouts.app')

@section('content')
<pagina tamanho="10">
    <painel titulo="Artigos">
        <p>
        <form class="form-inline text-center pull-right" action="{{route('site')}}" method="get">
            <input type="search" class="form-control" name="busca" placeholder="Buscar"
                   value="{{isset($busca) ? $busca: ''}}">
            <button class="btn btn-info">Buscar</button>

        </form>
        </p>
        <br><br><br>

        <div class="row">
    @foreach ($lista as $key => $value)
    <artigocard
            titulo="{{str_limit($value->titulo, 18, ' ...')}}"
            autor="{{$value->autor}}"
            data="{{$value->data}}"
            descricao="{{str_limit($value->descricao, 35, ' ...')}}"
            sm="6"
            md="4"
            link="{{route('artigo',[$value->id,str_slug($value->titulo)])}}"
            img="{{$value->imagem}}"
    >
    </artigocard>
  @endforeach
  </div>
  <div align="center">
            {{$lista}}
        </div>
    </painel>
</pagina>
@endsection