routes/web.php
<?php

use App\Artigo;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {
    if (isset($req->busca) && $req->busca != '') {
        $busca = $req->busca;
        //busca no db;
        $lista = Artigo::listaArtigosSite(3, $busca);
    } else {
        $lista = Artigo::listaArtigosSite(3);
        $busca = "";
    }


    return view('site', compact('lista', 'busca'));
})->name('site');
Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
        return view('artigo',compact('artigo'));
    }
    return redirect()->route('site');
})->name('artigo');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:eAutor');;
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArtigosController')->middleware('can:eAutor');
    Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
    Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
    Route::resource('adm', 'AdminController')->middleware('can:eAdmin');

});

app/Artigo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Artigo extends Model
{
    use SoftDeletes;

    protected $fillable = ['titulo', 'descricao', 'conteudo', 'data', 'imagem'];

    protected $dates=['deleted_at'];

    public function user(){
        return $this->belongsTo('App\User','user_id');
    }

    public static function listaArtigos($paginate){
        $user = auth()->user();
        if ($user->admin == 'S') {
            return DB::table('artigos')
                ->join('users', 'users.id', '=', 'artigos.user_id')
                ->select('artigos.id', 'artigos.titulo', 'artigos.descricao', 'users.name', 'artigos.data')
                ->whereNull('artigos.deleted_at')
                ->orderBy('artigos.id', 'DESC')
                ->paginate($paginate);
        } else {
            return DB::table('artigos')
                ->join('users', 'users.id', '=', 'artigos.user_id')
                ->select('artigos.id', 'artigos.titulo', 'artigos.descricao', 'users.name', 'artigos.data')
                ->whereNull('artigos.deleted_at')
                ->where('artigos.user_id', '=', $user->id)
                ->orderBy('artigos.id', 'DESC')
                ->paginate($paginate);
        }

                        
    }

    public static function listaArtigosSite($paginate, $busca = null)
    {
        return $busca ? DB::table('artigos')
            ->join('users', 'users.id', '=', 'artigos.user_id')
            ->select('artigos.id', 'artigos.titulo', 'artigos.descricao', 'users.name as autor', 'artigos.data', 'artigos.imagem')
            ->whereNull('artigos.deleted_at')
            ->whereDate('data', '<=', date('Y-m-d'))
            ->where(function ($query) use ($busca) {
                $query->orWhere('titulo', 'like', '%' . $busca . '%')
                    ->orWhere('descricao', 'like', '%' . $busca . '%');
            })
            ->orderBy('data', 'DESC')
            ->paginate($paginate) : DB::table('artigos')
            ->join('users', 'users.id', '=', 'artigos.user_id')
            ->select('artigos.id', 'artigos.titulo', 'artigos.descricao', 'users.name as autor', 'artigos.data', 'artigos.imagem')
            ->whereNull('artigos.deleted_at')
            ->whereDate('data', '<=', date('Y-m-d'))
            ->orderBy('data', 'DESC')
            ->paginate($paginate);
     }
}

app/Http/Controllers/Admin/ArtigosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Artigo;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Image;
use Validator;

class ArtigosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $listaMigalhas= json_encode([
            ['titulo'=> 'Admin','url'=>route('admin')],
            ['titulo'=> 'Lista de Artigos','url'=>''],
        ]);
        // $listaArtigos= Artigo::select('id','titulo','descricao','user_id','data')->paginate(5);
        // foreach ($listaArtigos as $key => $value) {
        //     $value->user_id = \App\User::find($value->user_id)->name;
        // }


        $listaArtigos=Artigo::listaArtigos(5);

        return view('admin.artigos.index',compact('listaMigalhas','listaArtigos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validacao = Validator::make($data, [
            "titulo"=>"required",
            "descricao"=>"required",
            "conteudo"=>"required",
            "data" => "required",
            "imagem" => "mimetypes:image/jpg,image/jpeg"
        ]);
        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        $path = $request->file('imagem')->store('img/bg');
        Image::make('storage/' . $path)->resize(1200, 630)->save('storage/' . $path);
        $data['imagem'] = 'storage/' . $path;
        $user = auth()->user();
        $user->artigos()->create($data);

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        return Artigo::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validacao = Validator::make($data, [
            "titulo"=>"required",
            "descricao"=>"required",
            "conteudo"=>"required",
            "data" => "required",
            "imagem" => "mimetypes:image/jpg,image/jpeg"
        ]);

        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        if (array_key_exists('imagem', $data)) {
            $path = $request->file('imagem')->store('img/bg');
            $data['imagem'] = 'storage/' . $path;
            Image::make('storage/' . $path)->resize(1200, 630)->save('storage/' . $path);
        }

        $user = auth()->user();
        $user->artigos()->find($id)->update($data);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Artigo::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/artigos/index.blade.php
@extends('layouts.app')

@section('content')
<pagina tamanho="12">
    @if($errors->all())

    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @foreach($errors->all() as $key => $value)
        <p>{{$value}}</p>
        @endforeach
    </div>

    @endif
    <painel titulo="Lista de artigos">

        <migalhas v-bind:lista="{{$listaMigalhas}}"></migalhas>
        <tabela-lista v-bind:titulos="['#','Título','Descrição','autor','Data']" v-bind:itens="{{json_encode($listaArtigos)}}" criar="#criar" detalhe="/admin/artigos/" editar="/admin/artigos/" deletar="/admin/artigos/" token="{{csrf_token()}}" ordem="desc" ordemcol="0" modal="sim">
        </tabela-lista>
        <div align="center">
            {{$listaArtigos}}
        </div>
    </painel>
</pagina>

<!-- MODAL ADD -->
<modal nome="adicionar" titulo="Adicionar">
    <formulario id="formAdicionar" css="" action="{{route('artigos.store')}}" method="post"
                enctype="multipart/form-data" token="{{csrf_token()}}">

        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Título" value="{{old('titulo')}}">
        </div>
        <div class="form-group">
            <label for="imagem">Imagem</label>
            <input class="form-control" type="file" name="imagem" id="imagem"
                   placeholder="O arquivo será redimensionado automaticamente" value="{{old('imagem')}}">
        </div>
        <div class="form-group">
            <label for="descricao">Descrição</label>
            <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição"
                   enctype="multipart/form-data" value="{{old('descricao')}}">
        </div>
        <div class="form-group">
            <label for="addConteudo">Conteudo</label>
            <ckeditor 
            id="addConteudo"
            name="conteudo"
            value="{{old('conteudo')}}" 
            :config="{
                toolbar: [
                    [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]
                ],
                height: 300
            }">
            </ckeditor>
        </div>

        <div class="form-group">
            <label for="data">Data</label>
            <input type="date" class="form-control" id="data" name="data" value="{{old('data')}}">
        </div>


    </formulario>
    <span slot="botoes"><button form="formAdicionar" class="btn btn-info">Adicionar</button></span>

</modal>

<!-- MODAL EDIT -->
<modal nome="editar" titulo="Editar">
    <formulario id="formEditar" css="" v-bind:action="'/admin/artigos/' + $store.state.item.id" method="put" enctype="multipart/form-data" token="{{csrf_token()}}">
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" class="form-control" id="titulo" name="titulo" v-model="$store.state.item.titulo" placeholder="Título">
        </div>

        {{--        <div class="form-group">--}}
        {{--            <label for="imagem">Imagem</label>--}}
        {{--            <input type="image" class="form-control" id="imagem" name="imagem" >--}}
        {{--        </div>--}}
        <div class="container2">
            <div class="form-group">
                <label for="imagem">Imagem</label>
                <img class="img" :src="'../'+$store.state.item.imagem">
                <input class="form-control" type="file" name="imagem" id="imagem"
                       placeholder="O arquivo será redimensionado automaticamente">
            </div>
        </div>

        <div class="form-group">
            <label for="descricao">Descrição</label>
            <input type="text" class="form-control" id="descricao" v-model="$store.state.item.descricao" name="descricao" placeholder="Descrição">
        </div>
        <div class="form-group">
            <label for="editconteudo">Conteudo</label>
            <ckeditor
                    id="editconteudo"
                    name="conteudo"
                    v-model="$store.state.item.conteudo"
                    :config="{
                 toolbar: [[ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'Custom Button' ]],
                height: 300
            }"
            >
            </ckeditor>

            {{--        subistituir por:    //https://github.com/ankurk91/vue-trumbowyg--}}
        </div>

        <div class="form-group">
            <label for="data">Data</label>
            <input type="date" class="form-control" id="data" name="data" v-model="$store.state.item.data">
        </div>


    </formulario>
    <span slot="botoes"> <button form="formEditar" class="btn btn-info">Adicionar</button></span>
</modal>

<!-- MODAL DETAIL -->
<modal nome="detalhe" v-bind:titulo="$store.state.item.titulo">

    <p>@{{$store.state.item.descricao}}</p>
    <br>
    <p>@{{$store.state.item.conteudo}}</p>


</modal>
@endsection
<style>
    .img {
        width: 100% !important;
    }
</style>