routes/web.php
<?php

use App\Artigo;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {
    if (isset($req->busca) && $req->busca != '') {
        $busca = $req->busca;
        //busca no db;
        $lista = Artigo::listaArtigosSite(3, $busca);
    } else {
        $lista = Artigo::listaArtigosSite(3);
        $busca = "";
    }


    return view('site', compact('lista', 'busca'));
})->name('site');
Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
        return view('artigo',compact('artigo'));
    }
    return redirect()->route('site');
})->name('artigo');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:eAutor');;
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArtigosController')->middleware('can:eAutor');
    Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
    Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
    Route::resource('adm', 'AdminController')->middleware('can:eAdmin');

});

app/Http/Controllers/Admin/AutoresController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Validation\Rule;

class AutoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listaMigalhas= json_encode([
            ['titulo'=> 'Admin','url'=>route('admin')],
            ['titulo'=> 'Lista de Autores','url'=>''],
        ]);
        $listaModelo= User::select('id','name','email')->where('autor','=','S')->paginate(5);

        
        return view('admin.autores.index',compact('listaMigalhas','listaModelo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validacao =\Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ]);

        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        // dd($request->all());
        $data['password'] = bcrypt($data['password']);
        User::create($data);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return User::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        if(isset($data['password']) && $data['password'] != ""){
            $validacao = \Validator::make($data,[
                'name' => 'required|string|max:255',
                'email' => ['required','string','email','max:255',Rule::unique('users')->ignore($id)],
                'password' => 'required|string|min:6',
            ]);
            $data['password'] = bcrypt($data['password']);
        }else{
            $validacao = \Validator::make($data,[
                'name' => 'required|string|max:255',
                'email' => ['required','string','email','max:255',Rule::unique('users')->ignore($id)],
            ]);
            unset($data['password']);
        }
        

        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        // dd($request->all());
        User::find($id)->update($data);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/autores/index.blade.php
@extends('layouts.app')

@section('content')
<pagina tamanho="12">
    @if($errors->all())
    
    <div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  @foreach($errors->all() as $key => $value)
  <p>{{$value}}</p>
  @endforeach
</div>
    
    @endif
    <painel titulo="Lista de Autores">
    
        <migalhas v-bind:lista="{{$listaMigalhas}}"></migalhas>
        <tabela-lista v-bind:titulos="['#','Nome','Email']" v-bind:itens="{{json_encode($listaModelo)}}" criar="#criar" detalhe="/admin/autores/" editar="/admin/autores/" ordem="asc" ordemcol="2" modal="sim">
        </tabela-lista>
    <div align="center">
    {{$listaModelo}}
    </div>
    </painel>
</pagina>

<!-- MODAL ADD -->
<modal nome="adicionar" titulo="Adicionar">
    <formulario id="formAdicionar" css="" action="{{route('autores.store')}}" method="post" enctype="" token="{{csrf_token()}}">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Nome" value="{{old('name')}}">
        </div>
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{old('email')}}">
        </div>
        <div class="form-group">
            <label for="autor">Autor</label>
            <select name="autor" id="autor" class="form-control">
                <option {{(old('autor') && old('autor') == 'N' ? 'selected' :'')}} value="N">Não</option>
                <option {{(old('autor') && old('autor') == 'S' ? 'selected' :'')}} {{(!old('autor') ? 'selected' :'')}} value="S">Sim</option>
            </select>
        </div>

        <div class="form-group">
            <label for="password">Senha</label>
            <input type="password" class="form-control" id="password" name="password" value="{{old('password')}}">
        </div>


    </formulario>
    <span slot="botoes"><button form="formAdicionar" class="btn btn-info">Adicionar</button></span>

</modal>

<!-- MODAL EDIT -->
<modal nome="editar" titulo="Editar">
    <formulario id="formEditar" css="" v-bind:action="'/admin/autores/' + $store.state.item.id" method="put" enctype="multipart/form-data" token="{{csrf_token()}}">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="name" name="name" v-model="$store.state.item.name" placeholder="Nome">
        </div>
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" class="form-control" id="email" v-model="$store.state.item.email" name="email" placeholder="E-mail">
        </div>
        <div class="form-group">
            <label for="autor">Autor</label>
            <select name="autor" v-model="$store.state.item.autor" id="autor"  class="form-control">
                <option  value="N">Não</option>
                <option  value="S">Sim</option>
            </select>
        </div>

        <div class="form-group">
            <label for="password">Senha</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>


    </formulario>
    <span slot="botoes"> <button form="formEditar" class="btn btn-info">Adicionar</button></span>
</modal>

<!-- MODAL DETAIL -->
<modal nome="detalhe" v-bind:titulo="$store.state.item.name">

    <p>@{{$store.state.item.name}}</p>
<br>
    <p>@{{$store.state.item.email}}</p>

</modal>
@endsection